FORMAT: 1A
HOST: http://test13152.apiblueprint.org/

# Best API

Best is a simple API allowing consumers to view programming languages

## Questions Collection [/best]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "What is the best programming language?",
                "choices": [
                        "choice": "Java",
                        "choice": "Python",
                        "choice": "Objective-C",
                        "choice": "Ruby"
                    
                ]
            }
        ]